### ISSUE TITLE
When `source_file` is absent or `-`, read bytes from STDIN

### ISSUE THREAD

**Issue by salsferrazza** [GoogleCloudPlatform/market-data-transcoder#68]
This would enable the transcoder to be run in streaming mode for POSIX inputs, for example:

```
http -pb 'https://www.cmegroup.com/ftp/SBEFix/Production/secdef.dat.gz' \ 
| gunzip - \
| txcode --schema_file ../datacast/transcoder/test/FIX50SP2.CME.xml --factory fix --source_file_format_type line_delimited

ApplID: '310'
Asset: ES
CFICode: FFIXSX
Currency: USD
DisplayFactor: 0.01
HighLimitPrice: 456775.0
LastUpdateTime: '20221120170356000585'
LowLimitPrice: 400425.0
MarketSegmentID: '64'
MatchAlgorithm: F
MatchEventIndicator: '00000000'
MaturityMonthYear: '202409'
MaxPriceVariation: 600.0
MaxTradeVol: 3000.0
MinPriceIncrement: 25.0
MinPriceIncrementAmount: 12.5
MinTradeVol: 1.0
MsgType: SECURITYDEFINITION
NoEvents:
- EventTime: '20220617133000000000'
  EventType: ACTIVATION
- EventTime: '20240920133000000000'
  EventType: LAST_ELIGIBLE_TRADE_DATE
NoInstrAttrib:
- InstrAttribType: TRADE_TYPE_ELIGIBILITY_DETAILS_FOR_SECURITY
  InstrAttribValue: '00000000000001000010000000001111'
NoLotTypeRules: '0'
NoMDFeedTypes:
- MDFeedType: GBX
  MarketDepth: 10
SecurityExchange: XCME
SecurityGroup: ES
SecurityID: '118'
SecurityIDSource: EXCHANGE_SYMBOL
SecurityType: FUTURE
SecurityUpdateAction: ADD
SettlPriceType: Final Actual Settlement at Clearing Tick
Symbol: ESU4
TradingReferenceDate: '20221123'
TradingReferencePrice: 428600.0
UnderlyingProduct: 5
UnitOfMeasure: Index Points
UnitOfMeasureQty: 50.0
UserDefinedInstrument: N
```
